version: '3'
services:
    apache-reverse-proxy:
        container_name: apache-reverse-proxy
        build: 
            context: ./apache-reverse-proxy
        networks:
            - default
        expose:
            - 80
        ports:
            - 80:80
    measureplatform-app:
        container_name: measureplatform-app
        build: 
            context: ./measure-platform
        entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "--", "java","-jar","measure-platform-1.0.1.war"]
        networks:
            - default
        depends_on:
            - apache-reverse-proxy
            - mysql-db
            - elasticsearch
            - kibana
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            # MeasurePlatform packaging
            - ZIP_URL=https://github.com/measureproduct/MeasurePlatform/releases/download/MeasurePlatform-1.0.1/MeasurePlatform.V1.0.1.zip
            - ZIP_FILE=MeasurePlatform.V1.0.1.zip
            - JAR_FILE=measure-platform-1.0.1.war
            # Datasource catalogue
            - ZIP_CATALOGUE_URL=https://github.com/measureproduct/DataSourceCatalog/releases/download/v1.0.0/DataSourceCatalog.zip
            - ZIP_CATALOGUE_FILE=DataSourceCatalog.zip
            # Datasources storage path (mandatory)
            - MEASURE_PLATFORM_STORAGE_MEASURE=/home/PackagedPlatform/storage/measures/
            - MEASURE_PLATFORM_STORAGE_APPLICATION=/home/PackagedPlatform/storage/applications/
            # Spring data jpa configuration (mandatory)
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/measureplatform?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DRIVER=com.mysql.jdbc.Driver
            # Mailing service configuration (optional)
            - SPRING_MAIL_USERNAME=
            - SPRING_MAIL_PASSWORD=
            - SPRING_MAIL_HOST=
            - SPRING_MAIL_PORT=
            - SPRING_MAIL_PROTOCOL=
            - SPRING_MAIL_TLS=
            - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=
            - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=
            - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=
        expose:
            - 8080
    qualityguard-app:
        container_name: qualityguard-app
        build: 
            context: ./qualityguard
        entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "--", "java","-jar","quality-guard-analysis-1.2.0.war"]
        networks:
            - default
        depends_on:
            - apache-reverse-proxy
            - measureplatform-app
            - mysql-db
            - elasticsearch
            - kibana
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            # QualityGuard packaging
            - ZIP_URL=https://github.com/measureproduct/QualityGuard/releases/download/v1.2.0/quality-guard-v1.2.0.zip
            - ZIP_FILE=quality-guard-v1.2.0.zip
            - JAR_FILE=quality-guard-analysis-1.2.0.war
            # Spring data jpa configuration
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/qualityguard?useUnicode=true&characterEncoding=utf8&useSSL=false
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DRIVER=com.mysql.jdbc.Driver
            # MeasurePlatform administrator
            - MEASURE_PLATFORM_LOGIN=admin
            - MEASURE_PLATFORM_PASSWORD=admin
            # Elasticsearch configuration (It should take the value of the elasticsearch environment variable "cluster.name")
            - ELASTICSEARCH_CLUSTER_NAME=docker-cluster
        expose:
            - 8085
    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        depends_on: 
            - apache-reverse-proxy
        volumes: 
            - ./data/sql-scripts:/docker-entrypoint-initdb.d/
        networks:
            - default
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=measureplatform
        expose:
            - 3306
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        depends_on: 
            - apache-reverse-proxy
        networks:
            - default
        environment:
            cluster.name: docker-cluster
            ES_JAVA_OPTS: -Xms2g -Xmx2g
            discovery.type: single-node
        expose:
            - 9200
            - 9300
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:6.5.4
        depends_on: 
            - apache-reverse-proxy
        networks:
            - default
        environment:
            SERVER_HOST: 0.0.0.0
            ELASTICSEARCH_URL: http://elasticsearch:9200
            SERVER_BASEPATH: /kibana
        depends_on:
            - elasticsearch
        expose:
            - 5601