version: '3'
services:
    apache-reverse-proxy:
        container_name: apache-reverse-proxy
        build: 
            context: ./apache-reverse-proxy
        networks:
            - default
        expose:
            - 80
        ports:
            - "80:80"
    measureplatform-app:
        container_name: measureplatform-app
        build: 
            context: ./measure-platform
        entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "--", "java","-jar","./measure-platform-1.0.0.war"]
        networks:
            - default
        depends_on:
            - apache-reverse-proxy
            - mysql-db
            - elasticsearch
            - kibana
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/measureplatform?useUnicode=true&characterEncoding=utf8&useSSL=false
        expose:
            - 8080
        ports:
            - 8080:8080
    qualityguardanalysis-app:
        container_name: qualityguardanalysis-app
        build: 
            context: ./qualityguardanalysis
        entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "--", "java","-jar","quality-guard-analysis-1.2.0.war"]
        networks:
            - default
        depends_on:
            - apache-reverse-proxy
            - measureplatform-app
            - mysql-db
            - elasticsearch
            - kibana
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/qualityguardanalysis?useUnicode=true&characterEncoding=utf8&useSSL=false
        expose:
            - 8085
        ports:
            - 8085:8085
    mysql-db:
        container_name: mysql-db
        build: ./mysql-db
        depends_on: 
            - apache-reverse-proxy
        entrypoint: 
            sh -c "echo 'CREATE DATABASE IF NOT EXISTS measureplatform; CREATE DATABASE IF NOT EXISTS qualityguardanalysis;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        networks:
            - default
        # environment:
        #     - MYSQL_ROOT_PASSWORD root
        #     - MYSQL_DATABASE measureplatform
        #     - MYSQL_USER user
        #     - MYSQL_PASSWORD user
        expose:
            - 3306
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        depends_on: 
            - apache-reverse-proxy
        networks:
            - default
        environment:
            cluster.name: docker-cluster
            ES_JAVA_OPTS: -Xms2g -Xmx2g
            discovery.type: single-node
        expose:
            - 9200
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:6.5.4
        depends_on: 
            - apache-reverse-proxy
        networks:
            - default
        environment:
            SERVER_HOST: 0.0.0.0
            ELASTICSEARCH_URL: http://elasticsearch:9200
            SERVER_BASEPATH: /kibana
        depends_on:
            - elasticsearch
        expose:
            - 5601
        ports:
            - "5601:5601"