version: '3'
services:
    measureplatform-app:
        build: 
            context: ./measure-platform
        #entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "-t", "0", "--", "java","-jar","measure-platform-0.9.0.war"]
        networks:
            - default
        depends_on:
            - mysql-db
            - elasticsearch
            - kibana
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            #- SPRING_PROFILES_ACTIVE=prod,swagger
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/measureplatform?useUnicode=true&characterEncoding=utf8&useSSL=false
            #- JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        expose:
            - 8080
        ports:
            - 8080:8080
    # qualityguardanalysis-app:
    #     build: 
    #         context: ./qualityguardanalysis
    #     #entrypoint: ["./wait-for-it.sh", "mysql-db:3306", "-t", "0", "--", "java","-jar","quality-guard-analysis-1.2.0.war"]
    #     networks:
    #         - default
    #     depends_on:
    #         - measureplatform-app
    #         - mysql-db
    #         - elasticsearch
    #         - kibana
    #     environment:
    #         - _JAVA_OPTIONS=-Xmx512m -Xms256m
    #         #- SPRING_PROFILES_ACTIVE=prod,swagger
    #         - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/qualityguardanalysis?useUnicode=true&characterEncoding=utf8&useSSL=false
    #         #- JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    #     expose:
    #         - 8085
    #     ports:
    #         - 8085:8085
    mysql-db:
        # extends:
        #     file: mysql.yml
        #     service: mysql-db
        build: ./mysql-db
        networks:
            - default
        #volumes:
        #     - ~/volumes/jhipster/MeasurePlatform/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=measureplatform
        expose:
            - 3306
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        networks:
            - default
        environment:
            - cluster.name=docker-cluster
            - ES_JAVA_OPTS=-Xms2g -Xmx2g
            - discovery.type=single-node
        expose:
            - 9200
            - 9300
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        networks:
            - default
        environment:
            - 'SERVER_HOST: 0.0.0.0'
            - 'ELASTICSEARCH_URL: http://elasticsearch:9200'
        depends_on:
            - elasticsearch
        expose:
            - 5601
        ports:
            - "5601:5601"