version: '2'
services:
    mysql:
        #container_name: measureplatform-mysql
        image: mysql:5.7.13
        networks:
            - default
        #volumes:
        #     - ~/volumes/jhipster/MeasurePlatform/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=measureplatform
        expose:
            - 3306        
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl